/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "places_airports.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

SearchResult *
closestairports_1(Target *argp, CLIENT *clnt)
{
	static SearchResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	
int resultCode = clnt_call (clnt, closestAirports,
		(xdrproc_t) xdr_Target, (caddr_t) argp,
		(xdrproc_t) xdr_SearchResult, (caddr_t) &clnt_res,
		TIMEOUT);
  
	if (resultCode != RPC_SUCCESS) {
		return (NULL);
	}
	
//	if (clnt_call (clnt, closestAirports,
//		(xdrproc_t) xdr_Target, (caddr_t) argp,
//		(xdrproc_t) xdr_SearchResult, (caddr_t) &clnt_res,
//		TIMEOUT) != RPC_SUCCESS) {
//		return (NULL);
//	}
	return (&clnt_res);
}
