/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places_airports.h"

bool_t
xdr_ClientRequest (XDR *xdrs, ClientRequest *objp)
{
	register int32_t *buf;

	if (!xdr_string (xdrs, &objp->city, 64))
		return FALSE;
	if (!xdr_string (xdrs, &objp->state, 3))
		return FALSE;
	return TRUE;
}

bool_t
xdr_PlacesAnswer (XDR *xdrs, PlacesAnswer *objp)
{
	register int32_t *buf;

	if (!xdr_string (xdrs, &objp->cityInfo, 128))
		return FALSE;
	if (!xdr_AirResults (xdrs, objp->airports))
		return FALSE;
	return TRUE;
}

bool_t
xdr_PlacesResult (XDR *xdrs, PlacesResult *objp)
{
	register int32_t *buf;

	if (!xdr_int (xdrs, &objp->err))
		return FALSE;
	switch (objp->err) {
		case 0:
			if (!xdr_PlacesAnswer (xdrs, &objp->PlacesResult_u.result))
				return FALSE;
			break;
		default:
			if (!xdr_string (xdrs, &objp->PlacesResult_u.errStr, 256))
				return FALSE;
			break;
	}
	return TRUE;
}


bool_t
xdr_Target (XDR *xdrs, Target *objp)
{
	register int32_t *buf;

	if (!xdr_double (xdrs, &objp->latitude))
		return FALSE;
	if (!xdr_double (xdrs, &objp->longitude))
		return FALSE;
	return TRUE;
}

bool_t
xdr_Airport (XDR *xdrs, Airport *objp)
{
	register int32_t *buf;

	if (!xdr_string (xdrs, &objp->code, 4))
		return FALSE;
	if (!xdr_string (xdrs, &objp->fullName, 64))
		return FALSE;
	if (!xdr_string (xdrs, &objp->state, 3))
		return FALSE;
	if (!xdr_double (xdrs, &objp->latitude))
		return FALSE;
	if (!xdr_double (xdrs, &objp->longitude))
		return FALSE;
	if (!xdr_float (xdrs, &objp->distanceToTarget))
		return FALSE;
	return TRUE;
}

bool_t
xdr_AirResults (XDR *xdrs, AirResults objp)
{
	register int32_t *buf;

	if (!xdr_vector (xdrs, (char *)objp, 5,
									 sizeof (Airport), (xdrproc_t) xdr_Airport))
		return FALSE;
	return TRUE;
}

bool_t
xdr_SearchResult (XDR *xdrs, SearchResult *objp)
{
	register int32_t *buf;

	if (!xdr_int (xdrs, &objp->err))
		return FALSE;
	switch (objp->err) {
		case 0:
			if (!xdr_AirResults (xdrs, objp->SearchResult_u.results))
				return FALSE;
			break;
		default:
			if (!xdr_string (xdrs, &objp->SearchResult_u.err, 256))
				return FALSE;
			break;
	}
	return TRUE;
}
